layout_spectrum: 0.03728794143535197
typography_spectrum: 0.24344165087677538
color:
  brandColors:
    - '#F2385A'
    - '#F5A503'
    - '#E9F1DF'
    - '#4AD9D9'
    - '#36B1BF'
  brandStrength: 0.2103976767975837
  lightness: 0.3659247774630785
  saturation: 0.6138870790600777
  rhythmicContrast: 0.2911227154545486
name: Cryptech
favicon: null
title: Cryptech Blog - under development
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
