name: Cryptech
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7354017260950059
title: Cryptech Blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d8dfd8'
    - '#bbb196'
    - '#47191b'
    - '#998473'
    - '#72514c'
  brandStrength: 0.8125
  lightness: 0.6875
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
